export interface Player {
  name: string;
  team: string;
  role: string;
}

export interface Category {
  name: string;
  players: Player[];
}

// Categories with proper player types from 2026 IPL squads
export const categories: Category[] = [
  {
    name: "Best Batter",
    players: [
      { name: "Virat Kohli", team: "RCB", role: "Batter" },
      { name: "Rohit Sharma", team: "MI", role: "Batter" },
      { name: "Shubman Gill", team: "GT", role: "Batter" },
      { name: "Yashasvi Jaiswal", team: "RR", role: "Batter" },
      { name: "Ruturaj Gaikwad", team: "CSK", role: "Batter" },
      { name: "KL Rahul", team: "DC", role: "Batter" },
      { name: "Suryakumar Yadav", team: "MI", role: "Batter" },
      { name: "Travis Head", team: "SRH", role: "Batter" },
      { name: "Sai Sudharsan", team: "GT", role: "Batter" },
      { name: "Tilak Varma", team: "MI", role: "Batter" },
      { name: "Rajat Patidar", team: "RCB", role: "Batter" },
      { name: "Shreyas Iyer", team: "PBKS", role: "Batter" },
      { name: "Devdutt Padikkal", team: "RCB", role: "Batter" },
    ],
  },
  {
    name: "Best Pacer",
    players: [
      { name: "Jasprit Bumrah", team: "MI", role: "Pacer" },
      { name: "Mohammed Shami", team: "LSG", role: "Pacer" },
      { name: "Arshdeep Singh", team: "PBKS", role: "Pacer" },
      { name: "Trent Boult", team: "MI", role: "Pacer" },
      { name: "Jofra Archer", team: "RR", role: "Pacer" },
      { name: "Kagiso Rabada", team: "GT", role: "Pacer" },
      { name: "Mohammed Siraj", team: "GT", role: "Pacer" },
      { name: "Mitchell Starc", team: "DC", role: "Pacer" },
      { name: "Pat Cummins", team: "SRH", role: "Pacer" },
      { name: "Josh Hazlewood", team: "RCB", role: "Pacer" },
      { name: "Lockie Ferguson", team: "PBKS", role: "Pacer" },
      { name: "Anrich Nortje", team: "KKR", role: "Pacer" },
      { name: "Prasidh Krishna", team: "RR", role: "Pacer" },
    ],
  },
  {
    name: "Best Captain",
    players: [
      { name: "Hardik Pandya", team: "MI", role: "Captain" },
      { name: "Rishabh Pant", team: "LSG", role: "Captain" },
      { name: "Shubman Gill", team: "GT", role: "Captain" },
      { name: "Shreyas Iyer", team: "PBKS", role: "Captain" },
      { name: "Ruturaj Gaikwad", team: "CSK", role: "Captain" },
      { name: "Rajat Patidar", team: "RCB", role: "Captain" },
      { name: "Sanju Samson", team: "RR", role: "Captain" },
      { name: "Axar Patel", team: "DC", role: "Captain" },
      { name: "Pat Cummins", team: "SRH", role: "Captain" },
      { name: "Ajinkya Rahane", team: "KKR", role: "Captain" },
      { name: "Ishan kishan", team: "SRH", role: "Captain" },
    ],
  },
  {
    name: "Best Wicketkeeper",
    players: [
      { name: "Rishabh Pant", team: "LSG", role: "WK-Batter" },
      { name: "Sanju Samson", team: "CSK", role: "WK-Batter" },
      { name: "MS Dhoni", team: "CSK", role: "WK-Batter" },
      { name: "Ishan Kishan", team: "SRH", role: "WK-Batter" },
      { name: "Jos Buttler", team: "GT", role: "WK-Batter" },
      { name: "KL Rahul", team: "DC", role: "WK-Batter" },
      { name: "Heinrich Klaasen", team: "SRH", role: "WK-Batter" },
      { name: "Nicholas Pooran", team: "LSG", role: "WK-Batter" },
      { name: "Quinton de Kock", team: "MI", role: "WK-Batter" },
      { name: "Dhruv Jurel", team: "RR", role: "WK-Batter" },
      { name: "Jitesh Sharma", team: "RCB", role: "WK-Batter" },
    ],
  },
  {
    name: "Best Spinner",
    players: [
      { name: "Rashid Khan", team: "GT", role: "Spinner" },
      { name: "Yuzvendra Chahal", team: "PBKS", role: "Spinner" },
      { name: "Kuldeep Yadav", team: "DC", role: "Spinner" },
      { name: "Varun Chakaravarthy", team: "KKR", role: "Spinner" },
      { name: "Ravi Bishnoi", team: "RR", role: "Spinner" },
      { name: "Sunil Narine", team: "KKR", role: "Spinner" },
      { name: "Noor Ahmad", team: "CSK", role: "Spinner" },
      { name: "Washington Sundar", team: "GT", role: "Spinner" },
      { name: "Krunal Pandya", team: "RCB", role: "Spinner" },
      { name: "Rahul Chahar", team: "CSK", role: "Spinner" },
      { name: "Suyash Sharma", team: "RCB", role: "Spinner" },
      { name: "Vipraj Nigam", team: "DC", role: "Spinner" },
      { name: "Manav Suthar", team: "GT", role: "Spinner" },
      { name: "Harpreet Brar", team: "PBKS", role: "Spinner" },
      { name: "Allah Ghazanfar", team: "MI", role: "Spinner" },
      { name: "Akeal Hosein", team: "CSK", role: "Spinner" },
      { name: "Harsh Dubey", team: "SRH", role: "Spinner" },
    ],
  },
  {
    name: "Best All-Rounder",
    players: [
      { name: "Hardik Pandya", team: "MI", role: "All-Rounder" },
      { name: "Ravindra Jadeja", team: "RR", role: "All-Rounder" },
      { name: "Axar Patel", team: "DC", role: "All-Rounder" },
      { name: "Cameron Green", team: "KKR", role: "All-Rounder" },
      { name: "Marcus Stoinis", team: "PBKS", role: "All-Rounder" },
      { name: "Venkatesh Iyer", team: "RCB", role: "All-Rounder" },
      { name: "Nitish Kumar Reddy", team: "SRH", role: "All-Rounder" },
      { name: "Shivam Dube", team: "CSK", role: "All-Rounder" },
      { name: "Krunal Pandya", team: "RCB", role: "All-Rounder" },
      { name: "Liam Livingstone", team: "SRH", role: "All-Rounder" },
      { name: "Mitchell Marsh", team: "LSG", role: "All-Rounder" },
      { name: "Ramandeep Singh", team: "KKR", role: "All-Rounder" },
      { name: "Marco Jansen", team: "PBKS", role: "All-Rounder" },
    ],
  },

  {
    name: "Best Opener",
    players: [
      { name: "Vaibhav Sooryavanshi", team: "RR", role: "Opener" },
      { name: "Yashasvi Jaiswal", team: "RR", role: "Opener" },
      { name: "Virat Kohli", team: "RCB", role: "Opener" },
      { name: "Shubman Gill", team: "GT", role: "Opener" },
      { name: "Travis Head", team: "SRH", role: "Opener" },
      { name: "Ruturaj Gaikwad", team: "CSK", role: "Opener" },
      { name: "Rohit Sharma", team: "MI", role: "Opener" },
      { name: "Abhishek Sharma", team: "SRH", role: "Opener" },
      { name: "Jos Buttler", team: "GT", role: "Opener" },
      { name: "Phil Salt", team: "RCB", role: "Opener" },
      { name: "Quinton de Kock", team: "MI", role: "Opener" },
      { name: "KL Rahul", team: "DC", role: "Opener" },
      { name: "Priyansh Arya", team: "PBKS", role: "Opener" },
      { name: "Prabhsimran Singh", team: "PBKS", role: "Opener" },
      { name: "Ishan Kishan", team: "SRH", role: "Opener" },
      { name: "Sai Sudharsan", team: "GT", role: "Opener" },
      { name: "Finn Allen", team: "KKR", role: "Opener" },
    ],
  },
  {
    name: "Best Finisher",
    players: [
      { name: "Rinku Singh", team: "KKR", role: "Finisher" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Finisher" },
      { name: "Tim David", team: "RCB", role: "Finisher" },
      { name: "Romario Shepherd", team: "RCB", role: "Finisher" },
      { name: "Nicholas Pooran", team: "LSG", role: "Finisher" },
      { name: "Hardik Pandya", team: "MI", role: "Finisher" },
      { name: "Shimron Hetmyer", team: "RR", role: "Finisher" },
      { name: "Rahul Tewatia", team: "GT", role: "Finisher" },
      { name: "David Miller", team: "DC", role: "Finisher" },
      { name: "Rovman Powell", team: "KKR", role: "Finisher" },
      { name: "Shahrukh Khan", team: "GT", role: "Finisher" },
      { name: "Shashank Singh", team: "PBKS", role: "Finisher" },
      { name: "Ashutosh Sharma", team: "DC", role: "Finisher" },
      { name: "Sameer Rizvi", team: "DC", role: "Finisher" },
      { name: "Marcus Stoinis", team: "PBKS", role: "Finisher" },
    ],
  },
  {
    name: "Best Death Bowler",
    players: [
      { name: "Jasprit Bumrah", team: "MI", role: "Death Bowler" },
      { name: "Arshdeep Singh", team: "PBKS", role: "Death Bowler" },
      { name: "Matheesha Pathirana", team: "KKR", role: "Death Bowler" },
      { name: "T.Natarajan", team: "DC", role: "Death Bowler" },
      { name: "Auqib Nabi", team: "DC", role: "Death Bowler" },
      { name: "Sandeep Sharma", team: "RR", role: "Death Bowler" },
      { name: "Eshan Malinga", team: "SRH", role: "Death Bowler" },
      { name: "Anshul Kamboj", team: "CSK", role: "Death Bowler" },
      { name: "Prince Yadav", team: "LSG", role: "Death Bowler" },
      { name: "Mohsin Khan", team: "LSG", role: "Death Bowler" },
      { name: "Bhuvneshwar Kumar", team: "RCB", role: "Death Bowler" },
      { name: "Josh Hazlewood", team: "RCB", role: "Death Bowler" },
      { name: "Jofra Archer", team: "RR", role: "Death Bowler" },
      { name: "Mohammed Shami", team: "LSG", role: "Death Bowler" },
    ],
  },

  {
    name: "Best Power Hitter",
    players: [
      { name: "Vaibhav Sooryavanshi", team: "RR", role: "Power Hitter" },
      { name: "Suryakumar Yadav", team: "MI", role: "Power Hitter" },
      { name: "Travis Head", team: "SRH", role: "Power Hitter" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Power Hitter" },
      { name: "Nicholas Pooran", team: "LSG", role: "Power Hitter" },
      { name: "Abhishek Sharma", team: "SRH", role: "Power Hitter" },
      { name: "Phil Salt", team: "RCB", role: "Power Hitter" },
      { name: "Tim David", team: "RCB", role: "Power Hitter" },
      { name: "Liam Livingstone", team: "SRH", role: "Power Hitter" },
      { name: "Rovman Powell", team: "KKR", role: "Power Hitter" },
      { name: "Rinku Singh", team: "KKR", role: "Power Hitter" },
      { name: "Marcus Stoinis", team: "PBKS", role: "Power Hitter" },
      { name: "Jos Buttler", team: "GT", role: "Power Hitter" },
      { name: "Priyansh Arya", team: "PBKS", role: "Power Hitter" },
      { name: "Tristan Stubbs", team: "DC", role: "Power Hitter" },
      { name: "Sameer Rizvi", team: "DC", role: "Power Hitter" },
      { name: "Prabhsimran Singh", team: "PBKS", role: "Power Hitter" },
    ],
  },
  {
    name: "Best Anchor",
    players: [
      { name: "Virat Kohli", team: "RCB", role: "Anchor" },
      { name: "Shubman Gill", team: "GT", role: "Anchor" },
      { name: "Ruturaj Gaikwad", team: "CSK", role: "Anchor" },
      { name: "KL Rahul", team: "DC", role: "Anchor" },
      { name: "Shreyas Iyer", team: "PBKS", role: "Anchor" },
      { name: "Sai Sudharsan", team: "GT", role: "Anchor" },
      { name: "Tilak Varma", team: "MI", role: "Anchor" },
      { name: "Yashasvi Jaiswal", team: "RR", role: "Anchor" },
      { name: "Rohit Sharma", team: "MI", role: "Anchor" },
      { name: "Ajinkya Rahane", team: "KKR", role: "Anchor" },
      { name: "Rajat Patidar", team: "RCB", role: "Anchor" },
      { name: "Devdutt Padikkal", team: "RCB", role: "Anchor" },
      { name: "Riyan Parag", team: "RR", role: "Anchor" },
      { name: "Sanju Samson", team: "CSK", role: "Anchor" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Anchor" },
    ],
  },
  {
    name: "Best Swing Bowler",
    players: [
      { name: "Bhuvneshwar Kumar", team: "RCB", role: "Swing Bowler" },
      { name: "Trent Boult", team: "MI", role: "Swing Bowler" },
      { name: "Deepak Chahar", team: "MI", role: "Swing Bowler" },
      { name: "Mohammed Shami", team: "LSG", role: "Swing Bowler" },
      { name: "Arshdeep Singh", team: "PBKS", role: "Swing Bowler" },
      { name: "Mitchell Starc", team: "DC", role: "Swing Bowler" },
      { name: "Mukesh Kumar", team: "DC", role: "Swing Bowler" },
      { name: "Vaibhav Arora", team: "KKR", role: "Swing Bowler" },
      { name: "Mukesh Choudhary", team: "CSK", role: "Swing Bowler" },
      { name: "Sandeep Sharma", team: "RR", role: "Swing Bowler" },
      { name: "Marco Jansen", team: "PBKS", role: "Swing Bowler" },
      { name: "Khaleel Ahmed", team: "CSK", role: "Swing Bowler" },
      { name: "Akash Deep", team: "RCB", role: "Swing Bowler" },
    ],
  },
  {
    name: "Best Express Pacer",
    players: [
      { name: "Jasprit Bumrah", team: "MI", role: "Express Pacer" },
      { name: "Ashok Sharma", team: "GT", role: "Express Pacer" },
      { name: "Jofra Archer", team: "RR", role: "Express Pacer" },
      { name: "Lockie Ferguson", team: "PBKS", role: "Express Pacer" },
      { name: "Mayank Yadav", team: "LSG", role: "Express Pacer" },
      { name: "Kagiso Rabada", team: "GT", role: "Express Pacer" },
      { name: "Anrich Nortje", team: "KKR", role: "Express Pacer" },
      { name: "Mohammed Siraj", team: "GT", role: "Express Pacer" },
      { name: "Jamie Overton", team: "SRH", role: "Express Pacer" },
      { name: "Kartik Tyagi", team: "KKR", role: "Express Pacer" },
      { name: "Mitchell Starc", team: "DC", role: "Express Pacer" },
      { name: "Pat Cummins", team: "SRH", role: "Express Pacer" },
      { name: "Mohammed Shami", team: "LSG", role: "Express Pacer" },
    ],
  },
  {
    name: "Best Leg Spinner",
    players: [
      { name: "Rashid Khan", team: "GT", role: "Leg Spinner" },
      { name: "Yuzvendra Chahal", team: "PBKS", role: "Leg Spinner" },
      { name: "Varun Chakaravarthy", team: "KKR", role: "Leg Spinner" },
      { name: "Ravi Bishnoi", team: "RR", role: "Leg Spinner" },
      { name: "Rahul Chahar", team: "CSK", role: "Leg Spinner" },
      { name: "Mayank Markande", team: "MI", role: "Leg Spinner" },
      { name: "Suyash Sharma", team: "RCB", role: "Leg Spinner" },
      { name: "Zeeshan Ansari", team: "SRH", role: "Leg Spinner" },
    ],
  },
  {
    name: "Best Left-Arm Spinner",
    players: [
      { name: "Ravindra Jadeja", team: "RR", role: "Left-Arm Spinner" },
      { name: "Axar Patel", team: "DC", role: "Left-Arm Spinner" },
      { name: "Kuldeep Yadav", team: "DC", role: "Left-Arm Spinner" },
      { name: "Shivang Kumar", team: "SRH", role: "Left-Arm Spinner" },
      { name: "Noor Ahmad", team: "CSK", role: "Left-Arm Spinner" },
      { name: "Krunal Pandya", team: "RCB", role: "Left-Arm Spinner" },
      { name: "Shahbaz Ahmed", team: "LSG", role: "Left-Arm Spinner" },
      { name: "Sai Kishore", team: "GT", role: "Left-Arm Spinner" },
      { name: "Harpreet Brar", team: "PBKS", role: "Left-Arm Spinner" },
      { name: "M Siddharth", team: "LSG", role: "Left-Arm Spinner" },
      { name: "Harsh Dubey", team: "SRH", role: "Left-Arm Spinner" },
      { name: "Mitchell Santner", team: "MI", role: "Left-Arm Spinner" },
      { name: "Manav Suthar", team: "GT", role: "Left-Arm Spinner" },
    ],
  },
  {
    name: "Best Foreign Player",
    players: [
      { name: "Travis Head", team: "SRH", role: "Overseas" },
      { name: "Jos Buttler", team: "GT", role: "Overseas" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Overseas" },
      { name: "Pat Cummins", team: "SRH", role: "Overseas" },
      { name: "Rashid Khan", team: "GT", role: "Overseas" },
      { name: "Jofra Archer", team: "RR", role: "Overseas" },
      { name: "Mitchell Starc", team: "DC", role: "Overseas" },
      { name: "Trent Boult", team: "MI", role: "Overseas" },
      { name: "Kagiso Rabada", team: "GT", role: "Overseas" },
      { name: "Phil Salt", team: "RCB", role: "Overseas" },
      { name: "Nicholas Pooran", team: "LSG", role: "Overseas" },
      { name: "Liam Livingstone", team: "SRH", role: "Overseas" },
      { name: "Marcus Stoinis", team: "PBKS", role: "Overseas" },
    ],
  },
  {
    name: "Best Indian Player",
    players: [
      { name: "Virat Kohli", team: "RCB", role: "Indian" },
      { name: "Rohit Sharma", team: "MI", role: "Indian" },
      { name: "Jasprit Bumrah", team: "MI", role: "Indian" },
      { name: "Rishabh Pant", team: "LSG", role: "Indian" },
      { name: "Hardik Pandya", team: "MI", role: "Indian" },
      { name: "Suryakumar Yadav", team: "MI", role: "Indian" },
      { name: "Shubman Gill", team: "GT", role: "Indian" },
      { name: "Yashasvi Jaiswal", team: "RR", role: "Indian" },
      { name: "Ravindra Jadeja", team: "RR", role: "Indian" },
      { name: "Ruturaj Gaikwad", team: "CSK", role: "Indian" },
      { name: "KL Rahul", team: "DC", role: "Indian" },
      { name: "Mohammed Shami", team: "LSG", role: "Indian" },
      { name: "Abhishek Sharma", team: "SRH", role: "Indian" },
    ],
  },
  {
    name: "Best T20 Specialist",
    players: [
      { name: "Sunil Narine", team: "KKR", role: "T20 Specialist" },
      { name: "Rashid Khan", team: "GT", role: "T20 Specialist" },
      { name: "Suryakumar Yadav", team: "MI", role: "T20 Specialist" },
      { name: "Andre Russell", team: "KKR", role: "T20 Specialist" },
      { name: "Nicholas Pooran", team: "LSG", role: "T20 Specialist" },
      { name: "Heinrich Klaasen", team: "SRH", role: "T20 Specialist" },
      { name: "Tim David", team: "RCB", role: "T20 Specialist" },
      { name: "Liam Livingstone", team: "SRH", role: "T20 Specialist" },
      { name: "Rinku Singh", team: "KKR", role: "T20 Specialist" },
      { name: "Phil Salt", team: "RCB", role: "T20 Specialist" },
      { name: "Rahul Tewatia", team: "GT", role: "T20 Specialist" },
      { name: "Marcus Stoinis", team: "PBKS", role: "T20 Specialist" },
    ],
  },
  {
    name: "Best Powerplay Batter",
    players: [
      { name: "Travis Head", team: "SRH", role: "Powerplay Batter" },
      { name: "Yashasvi Jaiswal", team: "RR", role: "Powerplay Batter" },
      { name: "Priyansh Arya", team: "PBKS", role: "Powerplay Batter" },
      { name: "Abhishek Sharma", team: "SRH", role: "Powerplay Batter" },
      { name: "Phil Salt", team: "RCB", role: "Powerplay Batter" },
      { name: "Jos Buttler", team: "GT", role: "Powerplay Batter" },
      { name: "Quinton de Kock", team: "MI", role: "Powerplay Batter" },
      { name: "Shubman Gill", team: "GT", role: "Powerplay Batter" },
      { name: "Rohit Sharma", team: "MI", role: "Powerplay Batter" },
      { name: "Virat Kohli", team: "RCB", role: "Powerplay Batter" },
      { name: "Sanju Samson", team: "CSK", role: "Powerplay Batter" },
      { name: "Prabhsimran Singh", team: "PBKS", role: "Powerplay Batter" },
      { name: "Finn allen", team: "KKR", role: "Powerplay Batter" },
      { name: "Ruturaj Gaikwad", team: "CSK", role: "Powerplay Batter" },
      { name: "KL Rahul", team: "DC", role: "Powerplay Batter" },
    ],
  },
  {
    name: "Best Powerplay Bowler",
    players: [
      { name: "Trent Boult", team: "MI", role: "Powerplay Bowler" },
      { name: "Mohammed Shami", team: "LSG", role: "Powerplay Bowler" },
      { name: "Josh Hazlewood", team: "RCB", role: "Powerplay Bowler" },
      { name: "Jasprit Bumrah", team: "MI", role: "Powerplay Bowler" },
      { name: "Deepak Chahar", team: "MI", role: "Powerplay Bowler" },
      { name: "Bhuvneshwar Kumar", team: "RCB", role: "Powerplay Bowler" },
      { name: "Marco Jansen", team: "PBKS", role: "Powerplay Bowler" },
      { name: "Pat Cummins", team: "SRH", role: "Powerplay Bowler" },
      { name: "Mitchell Starc", team: "DC", role: "Powerplay Bowler" },
      { name: "Kagiso Rabada", team: "GT", role: "Powerplay Bowler" },
      { name: "Mohammad Siraj", team: "GT", role: "Powerplay Bowler" },
      { name: "Arshdeep Singh", team: "PBKS", role: "Powerplay Bowler" },
      { name: "Prasidh Krishna", team: "RR", role: "Powerplay Bowler" },
      { name: "Mukesh Kumar", team: "DC", role: "Powerplay Bowler" },
    ],
  },
  {
    name: "Best Middle Order Batter",
    players: [
      { name: "Suryakumar Yadav", team: "MI", role: "Middle Order" },
      { name: "Tilak Varma", team: "MI", role: "Middle Order" },
      { name: "Shreyas Iyer", team: "PBKS", role: "Middle Order" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Middle Order" },
      { name: "Riyan Parag", team: "RR", role: "Middle Order" },
      { name: "Rinku Singh", team: "KKR", role: "Middle Order" },
      { name: "Hardik Pandya", team: "MI", role: "Middle Order" },
      { name: "Nicholas Pooran", team: "LSG", role: "Middle Order" },
      { name: "Rajat Patidar", team: "RCB", role: "Middle Order" },
      { name: "Shivam Dube", team: "CSK", role: "Middle Order" },
      { name: "Rahul Tewatia", team: "GT", role: "Middle Order" },
    ],
  },
  {
    name: "Best Young Talent",
    players: [
      { name: "Yashasvi Jaiswal", team: "RR", role: "Young Talent" },
      { name: "Tilak Varma", team: "MI", role: "Young Talent" },
      { name: "Abhishek Sharma", team: "SRH", role: "Young Talent" },
      { name: "Riyan Parag", team: "RR", role: "Young Talent" },
      { name: "Nitish Kumar Reddy", team: "SRH", role: "Young Talent" },
      { name: "Dhruv Jurel", team: "RR", role: "Young Talent" },
      { name: "Mayank Yadav", team: "LSG", role: "Young Talent" },
      { name: "Sai Sudharsan", team: "GT", role: "Young Talent" },
      { name: "Rinku Singh", team: "KKR", role: "Young Talent" },
      { name: "Rachin Ravindra", team: "KKR", role: "Young Talent" },
    ],
  },
  {
    name: "Best Match Winner",
    players: [
      { name: "Virat Kohli", team: "RCB", role: "Match Winner" },
      { name: "Rohit Sharma", team: "MI", role: "Match Winner" },
      { name: "MS Dhoni", team: "CSK", role: "Match Winner" },
      { name: "Jasprit Bumrah", team: "MI", role: "Match Winner" },
      { name: "Rashid Khan", team: "GT", role: "Match Winner" },
      { name: "Suryakumar Yadav", team: "MI", role: "Match Winner" },
      { name: "Rinku Singh", team: "KKR", role: "Match Winner" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Match Winner" },
      { name: "Travis Head", team: "SRH", role: "Match Winner" },
      { name: "Yashasvi Jaiswal", team: "RR", role: "Match Winner" },
      { name: "Hardik Pandya", team: "MI", role: "Match Winner" },
      { name: "Andre Russell", team: "KKR", role: "Match Winner" },
      { name: "Sunil Narine", team: "KKR", role: "Match Winner" },
    ],
  },
  {
    name: "Best IPL Legend",
    players: [
      { name: "MS Dhoni", team: "CSK", role: "IPL Legend" },
      { name: "Virat Kohli", team: "RCB", role: "IPL Legend" },
      { name: "Rohit Sharma", team: "MI", role: "IPL Legend" },
      { name: "Sunil Narine", team: "KKR", role: "IPL Legend" },
      { name: "AB de Villiers", team: "RCB", role: "IPL Legend" },
      { name: "Chris Gayle", team: "RCB", role: "IPL Legend" },
      { name: "Lasith Malinga", team: "MI", role: "IPL Legend" },
      { name: "Shane Watson", team: "CSK", role: "IPL Legend" },
      { name: "David Warner", team: "SRH", role: "IPL Legend" },
      { name: "Kieron Pollard", team: "MI", role: "IPL Legend" },
      { name: "Andre Russell", team: "KKR", role: "IPL Legend" },
      { name: "Ravindra Jadeja", team: "RR", role: "IPL Legend" },
      { name: "Jasprit Bumrah", team: "MI", role: "IPL Legend" },
    ],
  },
  {
    name: "Best Under Pressure",
    players: [
      { name: "MS Dhoni", team: "CSK", role: "Clutch Player" },
      { name: "Virat Kohli", team: "RCB", role: "Clutch Player" },
      { name: "Jasprit Bumrah", team: "MI", role: "Clutch Player" },
      { name: "Rinku Singh", team: "KKR", role: "Clutch Player" },
      { name: "Heinrich Klaasen", team: "SRH", role: "Clutch Player" },
      { name: "Rahul Tewatia", team: "GT", role: "Clutch Player" },
      { name: "Hardik Pandya", team: "MI", role: "Clutch Player" },
      { name: "Rashid Khan", team: "GT", role: "Clutch Player" },
      { name: "Suryakumar Yadav", team: "MI", role: "Clutch Player" },
      { name: "Rohit Sharma", team: "MI", role: "Clutch Player" },
      { name: "Ravindra Jadeja", team: "RR", role: "Clutch Player" },
      { name: "Pat Cummins", team: "SRH", role: "Clutch Player" },
      { name: "Rishabh Pant", team: "LSG", role: "Clutch Player" },
    ],
  },
];

export function getRandomCategory(): Category {
  return categories[Math.floor(Math.random() * categories.length)];
}

export function getInitials(name: string): string {
  return name
    .split(" ")
    .map((n) => n[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}
